[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"

# We need openssl to be statically linked on windows to avoid madness,
# and openssl-src does that based on the crt-static feature being
# enabled for the target, so let's turn that on here.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

# Local patch to avoid git submodule fetch issues on macOS
[patch."https://github.com/wezterm/xcb-imdkit-rs.git"]
xcb-imdkit = { path = "/Users/sunb/dev/sunb/xcb-imdkit-rs" }
